window.catalog = [{
    id: '0',
    dateAdded: '2017-05-15T16:58:40.000Z',
    title: 'Аляска',
    description: 'The best food for you and your friends.Филадельфия',
    placeholder: null,
    discountedPrice: 145,
    price: 145,
    popularity: 1,
    hasNew: true,
    category: ['суши', 'presentation'],
    weight: 285,
    info: {'грамм':'215','калорий':'400','гривен':'145'},
    ingredients: 'Рис, Нори, Авокадо, Огурец, Тобико, Лосось',
    size: 8,
    thumbnail: 'img/dishes/Alaska-600.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/dishes/alaska-big.jpg' // replace with paths to images extracted from item layout
},{
    id: '1',
    dateAdded: '2017-05-15T16:58:40.000Z',
    title: 'Дракон',
    description: 'The best food for you and your friends.Филадельфия',
    placeholder: null,
    discountedPrice: 370, 
    price: 370,
    popularity: 1,
    hasNew: true,
    category: ['суши', 'presentation'],
    weight: 268,
    info: {'грамм':'243','калорий':'550','гривен':'370'},
    ingredients: 'Рис, Нори, Сыр сливочный, Авокадо, Угорь унаги, Кунжут, Соус унаги, Тобико, Креветка тигровая',
    size: 8,
    thumbnail: 'img/dishes/Dragon-600.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/dishes/Dragon-big.jpg' // replace with paths to images extracted from item layout
}, {
    id: '2',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'Филаделфия лосось',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 220,
    price: 220,
    popularity: 2,
    hasNew: true,
    category: ['суши', 'presentation'],
    info: {},
    weight: 300,
    info: {'грамм':'300','калорий':'450','гривен':'220'},
    ingredients: 'Рис, Нори, Сыр сливочный, Огурец, Лосось',
    size: 8,
    thumbnail: 'img/dishes/Fila-salmon-600.jpg', // replace with image extracted from item layout
    imgFull: 'img/dishes/Fila-salmon-big.jpg' // replace with paths to images extracted from item layout
}, {
    id: '3',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'Веган',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 60,
    price: 60,
    popularity: 3,
    hasNew: true,
    category: ['суши' , 'presentation'],
    info: {},
    weight: 188,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Рис, Нори, Авокадо, Кунжут, Соус унаги, Перец болгарский, Огурец',
    size: 8,
    thumbnail: 'img/dishes/vegan-600.jpg', // replace with image extracted from item layout
    imgFull: 'img/dishes/vegan-big.jpg' // replace with paths to images extracted from item layout
}, {
    id: '4',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'Веган тофу',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 65,
    price: 65,
    popularity: 4,
    hasNew: true,
    category: ['суши' , 'presentation'],
    info: {},
    weight: 145,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Рис, Нори, Огурец, Сыр тофу',
    size: 8,
    thumbnail: 'img/dishes/vegan-t-600.jpg', // replace with image extracted from item layout
    imgFull: 'img/dishes/vegan-t-big.jpg' // replace with paths to images extracted from item layout
}, {
    id: '5',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'Калифорния лосось',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 145,
    price: 145,
    popularity: 5,
    hasNew: true,
    category: ['суши' , 'presentation'],
    info: {},
    weight: 220,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Рис, Нори, Сыр сливочный, Авокадо, Лосось, Тобико',
    size: 8,
    thumbnail: 'img/dishes/California-salmon-600.jpg', // replace with image extracted from item layout
    imgFull: 'img/dishes/California-salmon-big.jpg' // replace with paths to images extracted from item layout
}, {
    id: '6',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'Компай',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 245,
    price: 245,
    popularity: 6,
    hasNew: true, //новинка false - нет, true - да
    category: ['суши', 'best-sellers'], //категории и подкатегории
    info: {},
    weight: 260,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Рис, Нори, Сыр сливочный, Авокадо, Тобико, Лосось, Угорь унаги', // вес сэта
    size: 8, //сколько штук в сэте
    thumbnail: 'img/dishes/kampai-600.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/dishes/kampai-big.jpg' // replace with paths to images extracted from item layout
}, {
    id: '7',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'Филаделфия с креветкой',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 210,
    price: 210,
    popularity: 7,
    hasNew: true,
    category: ['суши'],
    info: {},
    weight: 195,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Рис, Нори, Сыр сливочный, Креветка салатная, Креветка тигровая',
    size: 8,
    thumbnail: 'img/dishes/fila-krev-600.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/dishes/fila-krev-big.jpg' // replace with paths to images extracted from item layout
}, {
    id: '8',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'Филадельфия двойной лосось',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 260,
    price: 260,
    popularity: 8,
    hasNew: false,
    category: ['суши'],
    info: {},
    weight: 300,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Рис, Нори, Сыр сливочный, Лосось',
    size: 8,
    thumbnail: 'img/dishes/Fila-salmon-salmon-600.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/dishes/Fila-salmon-salmon-big.jpg' // replace with paths to images extracted from item layout
}, {
    id: '9',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'Филаделфия с угорём',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 280,
    price: 280,
    popularity: 9,
    hasNew: false,
    category: ['суши', 'пицца'],
    info: {},
    weight: 278,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Рис, Нори, Сыр сливочный, Авокадо, Угорь унаги, Кунжут, Соус унаги',
    size: 8,
    thumbnail: 'img/dishes/Fila-acne-600.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/dishes/Fila-acne-big.jpg' // replace with paths to images extracted from item layout
}, {
    id: '10',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'Маки с креветкой',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85,
    price: 85,
    popularity: 1,
    hasNew: false,
    category: ['суши'],
    info: {},
    weight: 120,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Рис, Нори, Креветка салатная',
    size: 6,
    thumbnail: 'img/dishes/maki-krev-600.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/dishes/maki-krev-big.jpg' // replace with paths to images extracted from item layout
}, {
    id: '11',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'Маки с лососем',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85,
    price: 85,
    popularity: 1,
    hasNew: false,
    category: ['суши'],
    info: {},
    weight: 120,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Рис, Нори, Лосось',
    size: 6,
    thumbnail: 'img/dishes/maki-salmon-600.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/dishes/maki-salmon-big.jpg' // replace with paths to images extracted from item layout
},
{
    id: '12',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'Маки с угорём',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 95,
    price: 95,
    popularity: 1,
    hasNew: false,
    category: ['суши'],
    info: {},
    weight: 120,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Рис, Нори, Угорь унаги',
    size: 6,
    thumbnail: 'img/dishes/maki-acne-600.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/dishes/maki-acne-big.jpg', // replace with paths to images extracted from item layout
}, {
    id: '13',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'Креветки в темпуре Унаги',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 220,
    price: 220,
    popularity: 1,
    hasNew: false,
    category: ['суши'],
    info: {},
    weight: 250,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Креветка тигровая, Мука, Соль',
    size: 6,
    thumbnail: 'img/dishes/shrimp-lime-600.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/dishes/shrimp-lime-big.jpg' // replace with paths to images extracted from item layout
}, {
    id: '14',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'Мидии с соусом Унаги острые',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 225,
    price: 225,
    popularity: 1,
    hasNew: false,
    category: ['суши'],
    info: {},
    weight: 170,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Соус ширача, Мидии, Кунжут, Майонез, Сыр моцарелла, Соус унаги, Тобико',
    size: 6,
    thumbnail: 'img/dishes/Unagi-mussels-spicy-600.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/dishes/Unagi-mussels-spicy-big.jpg', // replace with paths to images extracted from item layout
},
/*{
    id: '15',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['sushi'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/dishes/item-суши-2.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/dishes/item-big.jpg',
}, {
    id: '16',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 90,
    price: 120,
    popularity: 1,
    hasNew: false,
    category: ['sushi'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/dishes/item-напитки.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/dishes/item-big-drink.jpg',
}, {
    id: '17',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['sushi'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/dishes/item-суши-2.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/dishes/item-big.jpg',
}, 
{
    id: '18',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['sushi'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/dishes/item-common.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/dishes/item-big.jpg',
}, {
    id: '19',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 90,
    price: 120,
    popularity: 1,
    hasNew: true,
    category: ['суши', 'best-sellers'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/dishes/item-пицца.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/dishes/item-big-pizza.jpg',
}, {
    id: '20',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: true,
    category: ['суши', 'best-sellers'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/dishes/item-суши-2.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/dishes/item-big.jpg',
},
{
    id: '21',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['суши', 'best-sellers'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/dishes/item-common.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/dishes/item-big.jpg',
}, {
    id: '22',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 10,
    price: 120,
    popularity: 1,
    hasNew: true,
    category: ['суши', 'best-sellers'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/dishes/item-common.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/dishes/item-big.jpg' // replace with paths to images extracted from item layout
}, {
    id: '23',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['суши', 'best-sellers'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','рыбы':'320 гр','риса':'320 гр', 'процент':'50 %', 'майонеза': '10 гр'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/dishes/item-common.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/dishes/item-big.jpg' // replace with paths to images extracted from item layout
},*/];


window.catalog.sort(function(a,b){
    return a.id - b.id;
})
